import type { UserPreferences } from '@/storage/types'
import { formatCurrentDateTimeContext } from '@/utils/dateTime'

const DEFAULT_AI_NAME = 'Assistant'
const DEFAULT_USER_NAME = 'the user'

export function getConfiguredAiName(preferences: UserPreferences): string {
	return preferences.aiName.trim() || DEFAULT_AI_NAME
}

export function getConfiguredUserName(preferences: UserPreferences): string {
	return preferences.userName.trim() || DEFAULT_USER_NAME
}

export function buildSystemInstruction(preferences: UserPreferences): string {
	const aiName = getConfiguredAiName(preferences)
	const userName = getConfiguredUserName(preferences)
	const behavior = preferences.aiBehaviorInstructions.trim()

	const sections = [
		`You are ${aiName}. You are speaking with ${userName}.`,
		`Current date and time: ${formatCurrentDateTimeContext()}.`,
		behavior
			? behavior
			: 'Be helpful, clear, and accurate. Match the user\'s tone when appropriate.',
		[
			'Application capabilities you must respect:',
			'- This app uses one continuous conversation.',
			'- Image, music, and video files are generated by separate models when the user asks with phrases like "generate an image of…". You cannot output JPEG/PNG files yourself.',
			'- If the user asks you to generate or draw an image, do not provide Midjourney, DALL-E, or Stable Diffusion prompts. Tell them to send a message starting with "generate an image of…" so the app uses the image model.',
			'- You can manage shared documents through the provided tools. Documents belong to both the user and you; there is no separate AI document library.',
			'- The full document library is injected into your context on every message (see below). Document tools and IndexedDB remain authoritative for changes.',
			'- Long-term memory entries from earlier conversation are also injected on every message. Treat them as durable facts unless the user updates them.',
			'- Older chat messages are archived into memory automatically; you only see the recent message window directly, plus the memory index.',
			'- Each message in the conversation includes its sent date and time. Use those timestamps for temporal reasoning.',
			'- Create and update documents using Markdown (headings, lists, bold, links, code blocks). Uploaded documents are read-only in the editor.',
			'- Use read_document if you need to confirm content after a recent edit, or when a document was omitted from context due to size limits.',
			'- Deleting a document requires user confirmation in the app UI.',
			'- Format replies with markdown when helpful: use blockquotes for quoted document excerpts, fenced code blocks for code, and headings for longer structured answers.',
		].join('\n'),
	]

	return sections.join('\n\n')
}
