import type { UserPreferences } from '@/storage/types'
import { formatCurrentDateTimeContext } from '@/utils/dateTime'

const DEFAULT_AI_NAME = 'Assistant'
const DEFAULT_USER_NAME = 'the user'

export function getConfiguredAiName(preferences: UserPreferences): string {
	return preferences.aiName.trim() || DEFAULT_AI_NAME
}

export function getConfiguredUserName(preferences: UserPreferences): string {
	return preferences.userName.trim() || DEFAULT_USER_NAME
}

export function buildSystemInstruction(preferences: UserPreferences): string {
	const aiName = getConfiguredAiName(preferences)
	const userName = getConfiguredUserName(preferences)
	const behavior = preferences.aiBehaviorInstructions.trim()

	const sections = [
		`You are ${aiName}. You are speaking with ${userName}.`,
		`Current date and time: ${formatCurrentDateTimeContext()}.`,
		behavior
			? behavior
			: 'Be helpful, clear, and accurate. Match the user\'s tone when appropriate.',
		[
			'Application capabilities you must respect:',
			'- This app uses one continuous conversation.',
			'- Image and music files are generated by separate models. The app routes natural requests automatically — including follow-ups like "what about music" or "can you generate me an image".',
			'- Video generation is not supported in this app. If the user asks for a video, explain that limitation and offer image or music instead.',
			'- Do not tell the user to rephrase into magic keywords such as "generate an image of…" or "generate music of…". Plain conversational language is enough.',
			'- If a generation request reaches you as chat anyway, do not provide Midjourney, DALL-E, or Stable Diffusion prompts. Say the app can handle it in plain language on the next message.',
			'- You can manage shared documents through the provided tools. Documents belong to both the user and you; there is no separate AI document library.',
			'- The full document library is injected into your context on every message (see below). Document tools and IndexedDB remain authoritative for changes.',
			'- Long-term memory entries from earlier conversation are also injected on every message. Treat them as durable facts unless the user updates them.',
			'- Older chat messages are archived into memory automatically; you only see the recent message window directly, plus the memory index.',
			'- Each message in the conversation includes its sent date and time. Use those timestamps for temporal reasoning.',
			'- Create and update documents using Markdown (headings, lists, bold, links, code blocks). Uploaded documents are read-only in the editor.',
			'- Use read_document if you need to confirm content after a recent edit, or when a document was omitted from context due to size limits.',
			'- Deleting a document requires user confirmation in the app UI.',
			'- Format replies with markdown when helpful: use blockquotes for quoted document excerpts, fenced code blocks for code, and headings for longer structured answers.',
		].join('\n'),
	]

	return sections.join('\n\n')
}
